name: DevSecOps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Security scan with npm audit
        run: npm audit --audit-level=high || true

      - name: Build Docker image
        run: docker build -t ghcr.io/oshadipalliyaguruge/cicd-demo:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/oshadipalliyaguruge/cicd-demo:latest
      
      - name: Security scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/oshadipalliyaguruge/cicd-demo:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true


  deploy:
      runs-on: ubuntu-latest
      needs: build-test-security

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'latest'

        - name: Configure Kubeconfig
          run: |
            mkdir -p $HOME/.kube
            echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

        - name: Deploy to Kubernetes
          run: |
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
