name: DevSecOps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Security scan with npm audit
        run: npm audit --audit-level=high || true

      - name: Containerize app (Docker build)
        run: |
          docker build -t CICD-demo .
      
      - name: Security scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'CICD-demo:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
